### ISSUE TITLE
How to define hotMod directory

### ISSUE THREAD

**Issue by lijiarui** [zixia/hot-import#8]
When I use this module I found the following error
```shell
Error: not found caller file?
    at callerResolve (/root/ticket-bot/node_modules/hot-import/src/hot-import.ts:210:11)
    at Object.<anonymous> (/root/ticket-bot/node_modules/hot-import/src/hot-import.ts:58:5)
    at Generator.next (<anonymous>)
    at /root/ticket-bot/node_modules/hot-import/dist/src/hot-import.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (/root/ticket-bot/node_modules/hot-import/dist/src/hot-import.js:3:12)
    at Object.hotImport (/root/ticket-bot/node_modules/hot-import/dist/src/hot-import.js:41:12)
    at /root/ticket-bot/src/logic/root.ts:164:22
    at Generator.next (<anonymous>)
    at /root/ticket-bot/src/logic/root.ts:7:71
(node:18884) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): TypeError: Cannot read property 'saveFlightData' of undefined
(node:18884) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
It seems it cannot find the module `hotMod = await hotImport('./service')` in my code.

I tried two kind of function to call the hotMod

1. When using docker, it works
2. When using npm to run, it seems it cannot find the path. 

Could you give a suggestion to define the path? Thanks

**Comment by huan** [comment]
### Need More Information

In order to help us to find the problem out, you should provide all the detail information about the issue. Please make sure you must  **provide the steps to reproduce the problem**.

**Comment by lijiarui** [comment]
I fix this by the following function
```ts
const path = require('path')
hotMod = await hotImport(path.join(__dirname, 'service')) 
```

**Comment by lijiarui** [comment]
Hot-import version: 0.1.24

`test.ts`
```ts

import {
  hotImport,
}                 from 'hot-import'

async function main () {
  try {
    let a = await hotImport('./test2')   
    setInterval(function() {
      console.log(a.test())
    }, 1 * 1000)
    
  } catch (error) {
    console.error(error)
  }
}

main()
```

`test2.ts`
```
export let a = {} as any

a.test = function() {
  return 'hello world'
}

export default a
```

`test.ts` and `test2.ts` in the same directory 

Run
```
➜  ticket-bot git:(master) ✗ ts-node test.ts
Error: not found caller file?
    at callerResolve (/Users/jiaruili/git/ticket-bot/node_modules/hot-import/src/hot-import.ts:210:11)
    at Object.<anonymous> (/Users/jiaruili/git/ticket-bot/node_modules/hot-import/src/hot-import.ts:58:5)
    at Generator.next (<anonymous>)
    at /Users/jiaruili/git/ticket-bot/node_modules/hot-import/dist/src/hot-import.js:7:71
    at Promise (<anonymous>)
    at __awaiter (/Users/jiaruili/git/ticket-bot/node_modules/hot-import/dist/src/hot-import.js:3:12)
    at Object.hotImport (/Users/jiaruili/git/ticket-bot/node_modules/hot-import/dist/src/hot-import.js:41:12)
    at /Users/jiaruili/git/ticket-bot/test.ts:8:19
    at Generator.next (<anonymous>)
    at /Users/jiaruili/git/ticket-bot/test.ts:7:71
```
